default: "warn"
base-store: "debug"
deploy-command: "debug"
local-store: "debug"
remote-and-local-store: "debug"
remote-and-local-store-spec: "debug"
s3-store: "debug"
make-artifact-git: "debug"
heroku-deployer: "info"
$: "info"
CLI: "debug"
